export { default as Header } from './Header'
export { default as HeroSection } from './HeroSection'
export { default as FeaturedCourses } from './FeaturedCourses'
export { default as WhyChooseUs } from './WhyChooseUs'
export { default as Testimonials } from './Testimonials'
export { default as HiringPartners } from './HiringPartners'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer'
